/* The following code was generated by JFlex 1.7.0 */


/****************************************************************************
 * En esta sección se puede incluir todo código que se copiará textualmente
 * al comienzo del archivo JAVA que contendrá la definición de la clase del 
 * analizador léxico.
 ****************************************************************************/

/* Ejemplo:


*/
package ejemplo.jflex;
import java.util.ArrayList;
import java_cup.runtime.*;
import java_cup.sym;
import java.nio.file.*;
import java.io.File;
import java.io.FileOutputStream; 
import java.io.OutputStream; 

/****************************************************************************
 * Las siguientes directivas afectan el comportamiento del analizador léxico:
 *
 *  - %class Nombre --> Nombre de la clase generada.
 *
 *  - %type Nombre  --> Nombre de la clase usada para representar token.
 *                      Será el tipo de los objetos retornados por yylex().
 *  - %line         --> El analizador sabrá el número de línea que se está
 *                      analizando. Puede consultarse con this.yyline
 *  - %column       --> El analizador sabrá el número de columna que se está
 *                      analizando. Puede consultarse con this.yycolumn
 *  - %char         --> El analizador sabrá el número de caracter que se está
 *                      analizando. Puede consultarse con this.yychar
 *
 * Existen otras directivas adicionales descriptas en la documentación.
 ****************************************************************************/ 

public class MiLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\17\1\57"+
    "\3\0\1\15\1\0\1\22\1\23\1\5\1\24\1\26\1\10\1\11"+
    "\1\4\1\7\11\6\1\27\1\25\1\20\1\14\1\21\2\0\5\12"+
    "\1\56\15\12\1\55\6\12\1\0\1\60\2\0\1\12\1\0\1\33"+
    "\1\54\1\36\1\51\1\46\1\44\1\12\1\45\1\34\2\12\1\47"+
    "\1\32\1\35\1\37\1\53\1\12\1\43\1\40\1\41\1\52\1\42"+
    "\1\50\3\12\1\30\1\16\1\31\54\0\1\12\12\0\1\12\4\0"+
    "\1\12\5\0\27\12\1\0\37\12\1\0\u01ca\12\4\0\14\12\16\0"+
    "\5\12\7\0\1\12\1\0\1\12\21\0\160\13\5\12\1\0\2\12"+
    "\2\0\4\12\1\0\1\12\6\0\1\12\1\0\3\12\1\0\1\12"+
    "\1\0\24\12\1\0\123\12\1\0\213\12\1\0\7\13\246\12\1\0"+
    "\46\12\2\0\1\12\7\0\47\12\11\0\55\13\1\0\1\13\1\0"+
    "\2\13\1\0\2\13\1\0\1\13\10\0\33\12\5\0\3\12\35\0"+
    "\13\13\5\0\53\12\37\13\4\0\2\12\1\13\143\12\1\0\1\12"+
    "\7\13\2\0\6\13\2\12\2\13\1\0\4\13\2\12\12\13\3\12"+
    "\2\0\1\12\20\0\1\12\1\13\36\12\33\13\2\0\131\12\13\13"+
    "\1\12\16\0\12\13\41\12\11\13\2\12\4\0\1\12\5\0\26\12"+
    "\4\13\1\12\11\13\1\12\3\13\1\12\5\13\22\0\31\12\3\13"+
    "\104\0\25\12\1\0\10\12\26\0\16\13\1\0\41\13\66\12\3\13"+
    "\1\12\22\13\1\12\7\13\12\12\2\13\2\0\12\13\1\0\20\12"+
    "\3\13\1\0\10\12\2\0\2\12\2\0\26\12\1\0\7\12\1\0"+
    "\1\12\3\0\4\12\2\0\1\13\1\12\7\13\2\0\2\13\2\0"+
    "\3\13\1\12\10\0\1\13\4\0\2\12\1\0\3\12\2\13\2\0"+
    "\12\13\2\12\17\0\3\13\1\0\6\12\4\0\2\12\2\0\26\12"+
    "\1\0\7\12\1\0\2\12\1\0\2\12\1\0\2\12\2\0\1\13"+
    "\1\0\5\13\4\0\2\13\2\0\3\13\3\0\1\13\7\0\4\12"+
    "\1\0\1\12\7\0\14\13\3\12\1\13\13\0\3\13\1\0\11\12"+
    "\1\0\3\12\1\0\26\12\1\0\7\12\1\0\2\12\1\0\5\12"+
    "\2\0\1\13\1\12\10\13\1\0\3\13\1\0\3\13\2\0\1\12"+
    "\17\0\2\12\2\13\2\0\12\13\11\0\1\12\7\0\3\13\1\0"+
    "\10\12\2\0\2\12\2\0\26\12\1\0\7\12\1\0\2\12\1\0"+
    "\5\12\2\0\1\13\1\12\7\13\2\0\2\13\2\0\3\13\10\0"+
    "\2\13\4\0\2\12\1\0\3\12\2\13\2\0\12\13\1\0\1\12"+
    "\20\0\1\13\1\12\1\0\6\12\3\0\3\12\1\0\4\12\3\0"+
    "\2\12\1\0\1\12\1\0\2\12\3\0\2\12\3\0\3\12\3\0"+
    "\14\12\4\0\5\13\3\0\3\13\1\0\4\13\2\0\1\12\6\0"+
    "\1\13\16\0\12\13\20\0\4\13\1\0\10\12\1\0\3\12\1\0"+
    "\27\12\1\0\20\12\3\0\1\12\7\13\1\0\3\13\1\0\4\13"+
    "\7\0\2\13\1\0\3\12\5\0\2\12\2\13\2\0\12\13\20\0"+
    "\1\12\3\13\1\0\10\12\1\0\3\12\1\0\27\12\1\0\12\12"+
    "\1\0\5\12\2\0\1\13\1\12\7\13\1\0\3\13\1\0\4\13"+
    "\7\0\2\13\7\0\1\12\1\0\2\12\2\13\2\0\12\13\1\0"+
    "\2\12\16\0\3\13\1\0\10\12\1\0\3\12\1\0\51\12\2\0"+
    "\1\12\7\13\1\0\3\13\1\0\4\13\1\12\5\0\3\12\1\13"+
    "\7\0\3\12\2\13\2\0\12\13\12\0\6\12\2\0\2\13\1\0"+
    "\22\12\3\0\30\12\1\0\11\12\1\0\1\12\2\0\7\12\3\0"+
    "\1\13\4\0\6\13\1\0\1\13\1\0\10\13\6\0\12\13\2\0"+
    "\2\13\15\0\60\12\1\13\2\12\7\13\5\0\7\12\10\13\1\0"+
    "\12\13\47\0\2\12\1\0\1\12\2\0\2\12\1\0\1\12\2\0"+
    "\1\12\6\0\4\12\1\0\7\12\1\0\3\12\1\0\1\12\1\0"+
    "\1\12\2\0\2\12\1\0\4\12\1\13\2\12\6\13\1\0\2\13"+
    "\1\12\2\0\5\12\1\0\1\12\1\0\6\13\2\0\12\13\2\0"+
    "\4\12\40\0\1\12\27\0\2\13\6\0\12\13\13\0\1\13\1\0"+
    "\1\13\1\0\1\13\4\0\2\13\10\12\1\0\44\12\4\0\24\13"+
    "\1\0\2\13\5\12\13\13\1\0\44\13\11\0\1\13\71\0\53\12"+
    "\24\13\1\12\12\13\6\0\6\12\4\13\4\12\3\13\1\12\3\13"+
    "\2\12\7\13\3\12\4\13\15\12\14\13\1\12\17\13\2\0\46\12"+
    "\1\0\1\12\5\0\1\12\2\0\53\12\1\0\u014d\12\1\0\4\12"+
    "\2\0\7\12\1\0\1\12\1\0\4\12\2\0\51\12\1\0\4\12"+
    "\2\0\41\12\1\0\4\12\2\0\7\12\1\0\1\12\1\0\4\12"+
    "\2\0\17\12\1\0\71\12\1\0\4\12\2\0\103\12\2\0\3\13"+
    "\40\0\20\12\20\0\126\12\2\0\6\12\3\0\u026c\12\2\0\21\12"+
    "\1\0\32\12\5\0\113\12\3\0\3\13\10\12\7\0\15\12\1\0"+
    "\4\12\3\13\13\0\22\12\3\13\13\0\22\12\2\13\14\0\15\12"+
    "\1\0\3\12\1\0\2\13\14\0\64\12\40\13\3\0\1\12\4\0"+
    "\1\12\1\13\2\0\12\13\41\0\3\13\2\0\12\13\6\0\130\12"+
    "\10\0\5\12\2\13\42\12\1\13\1\12\5\0\106\12\12\0\37\12"+
    "\1\0\14\13\4\0\14\13\12\0\12\13\36\12\2\0\5\12\13\0"+
    "\54\12\4\0\32\12\6\0\12\13\46\0\27\12\5\13\4\0\65\12"+
    "\12\13\1\0\35\13\2\0\13\13\6\0\12\13\15\0\1\12\10\0"+
    "\17\13\101\0\5\13\57\12\21\13\7\12\4\0\12\13\21\0\11\13"+
    "\14\0\3\13\36\12\15\13\2\12\12\13\54\12\16\13\14\0\44\12"+
    "\24\13\10\0\12\13\3\0\3\12\12\13\44\12\2\0\11\12\107\0"+
    "\3\13\1\0\25\13\4\12\1\13\4\12\3\13\2\12\1\0\2\13"+
    "\6\0\300\12\66\13\5\0\5\13\u0116\12\2\0\6\12\2\0\46\12"+
    "\2\0\6\12\2\0\10\12\1\0\1\12\1\0\1\12\1\0\1\12"+
    "\1\0\37\12\2\0\65\12\1\0\7\12\1\0\1\12\3\0\3\12"+
    "\1\0\7\12\3\0\4\12\2\0\6\12\4\0\15\12\5\0\3\12"+
    "\1\0\7\12\102\0\2\13\23\0\1\13\34\0\1\12\15\0\1\12"+
    "\20\0\15\12\63\0\41\13\21\0\1\12\4\0\1\12\2\0\12\12"+
    "\1\0\1\12\3\0\5\12\6\0\1\12\1\0\1\12\1\0\1\12"+
    "\1\0\4\12\1\0\13\12\2\0\4\12\5\0\5\12\4\0\1\12"+
    "\21\0\43\13\2\12\4\13\u032d\0\64\13\u0716\0\57\12\1\0\57\12"+
    "\1\0\205\12\6\0\4\12\3\13\2\12\14\0\46\12\1\0\1\12"+
    "\5\0\1\12\2\0\70\12\7\0\1\12\17\0\1\13\27\12\11\0"+
    "\7\12\1\0\7\12\1\0\7\12\1\0\7\12\1\0\7\12\1\0"+
    "\7\12\1\0\7\12\1\0\7\12\1\0\40\13\57\0\1\12\u01d5\0"+
    "\2\12\1\13\31\0\17\13\1\0\5\12\2\0\3\13\2\12\4\0"+
    "\126\12\2\0\2\13\2\0\3\12\1\0\132\12\1\0\4\12\5\0"+
    "\51\12\3\0\136\12\21\0\33\12\65\0\20\12\u0200\0\u19b6\12\112\0"+
    "\u51d6\12\52\0\u048d\12\103\0\56\12\2\0\u010d\12\3\0\20\12\12\13"+
    "\2\12\24\0\57\12\4\13\1\0\12\13\1\0\37\12\2\13\106\12"+
    "\14\13\45\0\11\12\2\0\147\12\2\0\44\12\1\0\10\12\77\0"+
    "\13\12\1\13\3\12\1\13\4\12\1\13\27\12\5\13\30\0\64\12"+
    "\14\0\2\13\62\12\22\13\12\0\12\13\6\0\22\13\6\12\3\0"+
    "\1\12\1\0\1\12\2\0\12\13\34\12\10\13\2\0\27\12\15\13"+
    "\14\0\35\12\3\0\4\13\57\12\16\13\16\0\1\12\12\13\6\0"+
    "\5\12\1\13\12\12\12\13\5\12\1\0\51\12\16\13\11\0\3\12"+
    "\1\13\10\12\2\13\2\0\12\13\6\0\27\12\3\0\1\12\3\13"+
    "\62\12\1\13\1\12\3\13\2\12\2\13\5\12\2\13\1\12\1\13"+
    "\1\12\30\0\3\12\2\0\13\12\5\13\2\0\3\12\2\13\12\0"+
    "\6\12\2\0\6\12\2\0\6\12\11\0\7\12\1\0\7\12\1\0"+
    "\53\12\1\0\12\12\12\0\163\12\10\13\1\0\2\13\2\0\12\13"+
    "\6\0\u2ba4\12\14\0\27\12\4\0\61\12\u2104\0\u016e\12\2\0\152\12"+
    "\46\0\7\12\14\0\5\12\5\0\1\12\1\13\12\12\1\0\15\12"+
    "\1\0\5\12\1\0\1\12\1\0\2\12\1\0\2\12\1\0\154\12"+
    "\41\0\u016b\12\22\0\100\12\2\0\66\12\50\0\14\12\4\0\20\13"+
    "\20\0\20\13\3\0\2\13\30\0\3\13\40\0\5\12\1\0\207\12"+
    "\23\0\12\13\7\0\32\12\4\0\1\13\1\0\32\12\13\0\131\12"+
    "\3\0\6\12\2\0\6\12\2\0\6\12\2\0\3\12\43\0\14\12"+
    "\1\0\32\12\1\0\23\12\1\0\2\12\1\0\17\12\2\0\16\12"+
    "\42\0\173\12\105\0\65\13\210\0\1\13\202\0\35\12\3\0\61\12"+
    "\17\0\1\13\37\0\40\12\20\0\21\12\1\13\10\12\1\13\5\0"+
    "\46\12\5\13\5\0\36\12\2\0\44\12\4\0\10\12\1\0\5\13"+
    "\52\0\236\12\2\0\12\13\6\0\44\12\4\0\44\12\4\0\50\12"+
    "\10\0\64\12\234\0\u0137\12\11\0\26\12\12\0\10\12\230\0\6\12"+
    "\2\0\1\12\1\0\54\12\1\0\2\12\3\0\1\12\2\0\27\12"+
    "\12\0\27\12\11\0\37\12\101\0\23\12\1\0\2\12\12\0\26\12"+
    "\12\0\32\12\106\0\70\12\6\0\2\12\100\0\1\12\3\13\1\0"+
    "\2\13\5\0\4\13\4\12\1\0\3\12\1\0\33\12\4\0\3\13"+
    "\4\0\1\13\40\0\35\12\3\0\35\12\43\0\10\12\1\0\34\12"+
    "\2\13\31\0\66\12\12\0\26\12\12\0\23\12\15\0\22\12\156\0"+
    "\111\12\67\0\63\12\15\0\63\12\u030d\0\3\13\65\12\17\13\37\0"+
    "\12\13\17\0\4\13\55\12\13\13\25\0\31\12\7\0\12\13\6\0"+
    "\3\13\44\12\16\13\1\0\12\13\20\0\43\12\1\13\2\0\1\12"+
    "\11\0\3\13\60\12\16\13\4\12\5\0\3\13\3\0\12\13\1\12"+
    "\1\0\1\12\43\0\22\12\1\0\31\12\14\13\6\0\1\13\101\0"+
    "\7\12\1\0\1\12\1\0\4\12\1\0\17\12\1\0\12\12\7\0"+
    "\57\12\14\13\5\0\12\13\6\0\4\13\1\0\10\12\2\0\2\12"+
    "\2\0\26\12\1\0\7\12\1\0\2\12\1\0\5\12\2\0\1\13"+
    "\1\12\7\13\2\0\2\13\2\0\3\13\2\0\1\12\6\0\1\13"+
    "\5\0\5\12\2\13\2\0\7\13\3\0\5\13\213\0\65\12\22\13"+
    "\4\12\5\0\12\13\46\0\60\12\24\13\2\12\1\0\1\12\10\0"+
    "\12\13\246\0\57\12\7\13\2\0\11\13\27\0\4\12\2\13\42\0"+
    "\60\12\21\13\3\0\1\12\13\0\12\13\46\0\53\12\15\13\10\0"+
    "\12\13\66\0\32\12\3\0\17\13\4\0\12\13\u0166\0\100\12\12\13"+
    "\25\0\1\12\u01c0\0\71\12\u0107\0\11\12\1\0\45\12\10\13\1\0"+
    "\10\13\1\12\17\0\12\13\30\0\36\12\2\0\26\13\1\0\16\13"+
    "\u0349\0\u039a\12\146\0\157\13\21\0\304\12\u0abc\0\u042f\12\u0fd1\0\u0247\12"+
    "\u21b9\0\u0239\12\7\0\37\12\1\0\12\13\146\0\36\12\2\0\5\13"+
    "\13\0\60\12\7\13\11\0\4\12\14\0\12\13\11\0\25\12\5\0"+
    "\23\12\u0370\0\105\12\13\0\1\12\56\13\20\0\4\13\15\12\100\0"+
    "\1\12\37\0\u17ed\12\23\0\u02f3\12\u250d\0\2\12\u0bfe\0\153\12\5\0"+
    "\15\12\3\0\11\12\7\0\12\12\3\0\2\13\u14c6\0\5\13\3\0"+
    "\6\13\10\0\10\13\2\0\7\13\36\0\4\13\224\0\3\13\u01bb\0"+
    "\125\12\1\0\107\12\1\0\2\12\2\0\1\12\2\0\2\12\2\0"+
    "\4\12\1\0\14\12\1\0\1\12\1\0\7\12\1\0\101\12\1\0"+
    "\4\12\2\0\10\12\1\0\7\12\1\0\34\12\1\0\4\12\1\0"+
    "\5\12\1\0\1\12\3\0\7\12\1\0\u0154\12\2\0\31\12\1\0"+
    "\31\12\1\0\37\12\1\0\31\12\1\0\37\12\1\0\31\12\1\0"+
    "\37\12\1\0\31\12\1\0\37\12\1\0\31\12\1\0\10\12\2\0"+
    "\62\13\u0200\0\67\13\4\0\62\13\10\0\1\13\16\0\1\13\26\0"+
    "\5\13\1\0\17\13\u0550\0\7\13\1\0\21\13\2\0\7\13\1\0"+
    "\2\13\1\0\5\13\u07d5\0\305\12\13\0\7\13\51\0\104\12\7\13"+
    "\5\0\12\13\u04a6\0\4\12\1\0\33\12\1\0\2\12\1\0\1\12"+
    "\2\0\1\12\1\0\12\12\1\0\4\12\1\0\1\12\1\0\1\12"+
    "\6\0\1\12\4\0\1\12\1\0\1\12\1\0\1\12\1\0\3\12"+
    "\1\0\2\12\1\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\1\0\1\12\1\0\1\12\1\0\2\12\1\0\1\12\2\0\4\12"+
    "\1\0\7\12\1\0\4\12\1\0\4\12\1\0\1\12\1\0\12\12"+
    "\1\0\21\12\5\0\3\12\1\0\5\12\1\0\21\12\u0274\0\32\13"+
    "\6\0\32\13\6\0\32\13\u0e76\0\ua6d7\12\51\0\u1035\12\13\0\336\12"+
    "\2\0\u1682\12\u295e\0\u021e\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\13\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\1\1\10\1\11\3\1\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\15\10\1\24"+
    "\1\25\1\26\1\27\1\30\2\0\2\31\2\0\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\2\10\1\40\1\41"+
    "\10\10\1\42\3\10\1\43\1\44\1\45\1\46\2\30"+
    "\2\0\1\47\1\50\1\10\1\51\13\10\1\0\1\30"+
    "\1\52\1\10\1\53\1\54\1\55\2\10\1\56\4\10"+
    "\1\57\1\10\1\60\1\61\1\62\2\10\1\63\2\10"+
    "\1\64\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\142\0\142\0\304\0\142"+
    "\0\365\0\u0126\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c"+
    "\0\u027d\0\u02ae\0\u02df\0\142\0\142\0\u0157\0\142\0\142"+
    "\0\142\0\142\0\142\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4"+
    "\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c"+
    "\0\142\0\u058d\0\142\0\u05be\0\u05ef\0\u0620\0\u0126\0\u0126"+
    "\0\u0651\0\u0682\0\u06b3\0\142\0\142\0\142\0\142\0\142"+
    "\0\142\0\u06e4\0\u0715\0\u01b9\0\u01b9\0\u0746\0\u0777\0\u07a8"+
    "\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d\0\u01b9\0\u08ce\0\u08ff"+
    "\0\u0930\0\142\0\142\0\142\0\142\0\u0961\0\142\0\u0992"+
    "\0\u09c3\0\142\0\142\0\u09f4\0\u01b9\0\u0a25\0\u0a56\0\u0a87"+
    "\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f"+
    "\0\u0c40\0\u0992\0\u01b9\0\u0c71\0\u01b9\0\u01b9\0\u01b9\0\u0ca2"+
    "\0\u0cd3\0\u01b9\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u01b9\0\u0dc8"+
    "\0\u01b9\0\u01b9\0\u01b9\0\u0df9\0\u0e2a\0\u01b9\0\u0e5b\0\u0e8c"+
    "\0\u01b9\0\u01b9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\3\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\15\1\35\1\15\1\36\1\15"+
    "\1\37\1\40\1\41\1\42\1\43\1\15\1\44\1\15"+
    "\1\45\1\46\1\47\1\15\1\50\2\15\1\51\1\3"+
    "\1\52\2\3\54\52\1\53\1\54\63\0\1\5\62\0"+
    "\1\55\1\56\61\0\2\11\1\0\1\57\55\0\2\60"+
    "\57\0\1\61\1\60\126\0\1\62\1\63\10\0\2\15"+
    "\2\0\2\15\16\0\25\15\16\0\1\64\61\0\1\65"+
    "\61\0\1\66\56\0\1\67\60\0\1\70\60\0\1\71"+
    "\52\0\2\15\2\0\2\15\16\0\1\15\1\72\23\15"+
    "\10\0\2\15\2\0\2\15\16\0\3\15\1\73\2\15"+
    "\1\74\3\15\1\75\12\15\10\0\2\15\2\0\2\15"+
    "\16\0\5\15\1\76\17\15\10\0\2\15\2\0\2\15"+
    "\16\0\13\15\1\77\11\15\10\0\2\15\2\0\2\15"+
    "\16\0\13\15\1\100\11\15\10\0\2\15\2\0\2\15"+
    "\16\0\1\15\1\101\23\15\10\0\2\15\2\0\2\15"+
    "\16\0\14\15\1\102\10\15\10\0\2\15\2\0\2\15"+
    "\16\0\15\15\1\103\7\15\10\0\2\15\2\0\2\15"+
    "\16\0\15\15\1\104\7\15\10\0\2\15\2\0\2\15"+
    "\16\0\13\15\1\105\11\15\10\0\2\15\2\0\2\15"+
    "\16\0\5\15\1\106\17\15\10\0\2\15\2\0\2\15"+
    "\16\0\3\15\1\107\21\15\10\0\2\15\2\0\2\15"+
    "\16\0\5\15\1\110\6\15\1\111\10\15\2\0\1\52"+
    "\2\0\54\52\37\0\1\112\3\0\1\113\1\0\1\114"+
    "\13\0\1\115\1\0\1\55\1\116\1\117\56\55\5\120"+
    "\1\121\53\120\6\0\2\61\1\0\1\57\60\0\1\122"+
    "\60\0\1\123\55\0\2\15\2\0\2\15\16\0\2\15"+
    "\1\124\22\15\10\0\2\15\2\0\2\15\16\0\7\15"+
    "\1\125\15\15\10\0\2\15\2\0\2\15\16\0\3\15"+
    "\1\126\21\15\10\0\2\15\2\0\2\15\16\0\5\15"+
    "\1\127\17\15\10\0\2\15\2\0\2\15\16\0\14\15"+
    "\1\130\10\15\10\0\2\15\2\0\2\15\16\0\11\15"+
    "\1\131\13\15\10\0\2\15\2\0\2\15\16\0\21\15"+
    "\1\132\3\15\10\0\2\15\2\0\2\15\16\0\5\15"+
    "\1\133\17\15\10\0\2\15\2\0\2\15\16\0\6\15"+
    "\1\134\16\15\10\0\2\15\2\0\2\15\16\0\2\15"+
    "\1\135\22\15\10\0\2\15\2\0\2\15\16\0\7\15"+
    "\1\136\15\15\10\0\2\15\2\0\2\15\16\0\5\15"+
    "\1\137\17\15\10\0\2\15\2\0\2\15\16\0\7\15"+
    "\1\140\15\15\4\0\1\117\56\0\5\120\1\141\57\120"+
    "\1\142\1\141\53\120\6\0\2\15\2\0\2\15\16\0"+
    "\3\15\1\143\21\15\10\0\2\15\2\0\2\15\16\0"+
    "\6\15\1\144\16\15\10\0\2\15\2\0\2\15\16\0"+
    "\16\15\1\145\6\15\10\0\2\15\2\0\2\15\16\0"+
    "\3\15\1\146\21\15\10\0\2\15\2\0\2\15\16\0"+
    "\6\15\1\147\16\15\10\0\2\15\2\0\2\15\16\0"+
    "\14\15\1\150\10\15\10\0\2\15\2\0\2\15\16\0"+
    "\1\15\1\151\23\15\10\0\2\15\2\0\2\15\16\0"+
    "\14\15\1\152\10\15\10\0\2\15\2\0\2\15\16\0"+
    "\15\15\1\153\7\15\10\0\2\15\2\0\2\15\16\0"+
    "\2\15\1\154\22\15\10\0\2\15\2\0\2\15\16\0"+
    "\15\15\1\155\7\15\10\0\2\15\2\0\2\15\16\0"+
    "\16\15\1\156\6\15\2\0\4\120\1\117\1\141\53\120"+
    "\6\0\2\15\2\0\2\15\16\0\7\15\1\157\15\15"+
    "\10\0\2\15\2\0\2\15\16\0\1\15\1\160\23\15"+
    "\10\0\2\15\2\0\2\15\16\0\7\15\1\161\15\15"+
    "\10\0\2\15\2\0\2\15\16\0\14\15\1\162\10\15"+
    "\10\0\2\15\2\0\2\15\16\0\15\15\1\163\7\15"+
    "\10\0\2\15\2\0\2\15\16\0\14\15\1\164\10\15"+
    "\10\0\2\15\2\0\2\15\16\0\14\15\1\165\10\15"+
    "\10\0\2\15\2\0\2\15\16\0\7\15\1\166\15\15"+
    "\10\0\2\15\2\0\2\15\16\0\1\15\1\167\23\15"+
    "\10\0\2\15\2\0\2\15\16\0\14\15\1\170\10\15"+
    "\10\0\2\15\2\0\2\15\16\0\3\15\1\171\21\15"+
    "\10\0\2\15\2\0\2\15\16\0\3\15\1\172\21\15"+
    "\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3773];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\2\11\1\1\1\11\13\1\2\11"+
    "\1\1\5\11\15\1\1\11\1\1\1\11\2\1\2\0"+
    "\2\1\2\0\6\11\20\1\4\11\1\1\1\11\2\0"+
    "\2\11\15\1\1\0\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /*************************************************************************
    * En esta sección se puede incluir código que se copiará textualmente
    * como parte de la definición de la clase del analizador léxico.
    * Típicamente serán variables de instancia o nuevos métodos de la clase.
    *************************************************************************/
    public byte[] entrada;
    public static String FILEPATH = "C:\\Users\\flynn\\ts.txt"; 
    public static File file = new File(FILEPATH);     
    public StringBuffer string = new StringBuffer();
    public ArrayList<MiToken> tablaDeSimbolos = new ArrayList<>();
 
    private MiToken token(String nombre) {
        return new MiToken(nombre, this.yyline, this.yycolumn);
    }

    private MiToken token(String nombre, Object valor) {
        return new MiToken(nombre, this.yyline, this.yycolumn, valor);
    }
   


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MiLexico(java.io.Reader in) {
      try {
        if (file.createNewFile()) {
            System.out.println("Archivo creado");
        }
    } catch(Exception e) {
            e.printStackTrace();
            System.out.println("Error al crear el archivo");
    }

    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3280) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
        System.out.println(tablaDeSimbolos.toString());
  yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Caracter no permitido: <" + yytext() + ">");
            } 
            // fall through
          case 54: break;
          case 2: 
            { /* Fin de Linea, se ignora*/
            } 
            // fall through
          case 55: break;
          case 3: 
            { /* Espacio en blanco no hace nada*/
            } 
            // fall through
          case 56: break;
          case 4: 
            { return token("DIVIDIDO", yytext());
            } 
            // fall through
          case 57: break;
          case 5: 
            { return token("POR", yytext());
            } 
            // fall through
          case 58: break;
          case 6: 
            { MiToken token = new MiToken("ENTERO", yytext());
                                  try {
                                    entrada = "ENTERO ".getBytes();
                                    Files.write(Paths.get(FILEPATH), entrada, StandardOpenOption.APPEND);
                                    entrada = (yytext() + "\n").getBytes();
                                    Files.write(Paths.get(FILEPATH), entrada, StandardOpenOption.APPEND);
                                    tablaDeSimbolos.add(token);

                                  } catch(Exception e) {
                                        e.printStackTrace();
                                        System.out.println("Error en grabando en el archivo token ENTERO");
                                  }

                                  return token;
            } 
            // fall through
          case 59: break;
          case 7: 
            { return token("MENOS", yytext());
            } 
            // fall through
          case 60: break;
          case 8: 
            { MiToken token = new MiToken("ID", yytext());
                                  try {
                                    entrada = "ID ".getBytes();
                                    Files.write(Paths.get(FILEPATH), entrada, StandardOpenOption.APPEND);
                                    entrada = (yytext() + "\n").getBytes();
                                    Files.write(Paths.get(FILEPATH), entrada, StandardOpenOption.APPEND);
                                    tablaDeSimbolos.add(token);

                                  } catch(Exception e) {
                                        e.printStackTrace();
                                        System.out.println("Error en grabando en el archivo token ID");
                                  }
                                  
                                  return token;
            } 
            // fall through
          case 61: break;
          case 9: 
            { return token("IGUAL", yytext());
            } 
            // fall through
          case 62: break;
          case 10: 
            { return token("MENOR", yytext());
            } 
            // fall through
          case 63: break;
          case 11: 
            { return token("MAYOR", yytext());
            } 
            // fall through
          case 64: break;
          case 12: 
            { return token("PARENABRE", yytext());
            } 
            // fall through
          case 65: break;
          case 13: 
            { return token("PARENCIERRA", yytext());
            } 
            // fall through
          case 66: break;
          case 14: 
            { return token("MAS", yytext());
            } 
            // fall through
          case 67: break;
          case 15: 
            { return token("PUNTO_COMA", yytext());
            } 
            // fall through
          case 68: break;
          case 16: 
            { return token("COMA", yytext());
            } 
            // fall through
          case 69: break;
          case 17: 
            { return token("DOSPUNTOS", yytext());
            } 
            // fall through
          case 70: break;
          case 18: 
            { return token("LLAVEABRE", yytext());
            } 
            // fall through
          case 71: break;
          case 19: 
            { return token("LLAVECIERRA", yytext());
            } 
            // fall through
          case 72: break;
          case 20: 
            { string.setLength(0); yybegin(STRING);
            } 
            // fall through
          case 73: break;
          case 21: 
            { string.append( yytext() );
            } 
            // fall through
          case 74: break;
          case 22: 
            { yybegin(YYINITIAL);
                                       MiToken token = new MiToken("STRING", 
                                       string.toString());
                                  try {
                                    entrada = "STRING ".getBytes();
                                    Files.write(Paths.get(FILEPATH), entrada, StandardOpenOption.APPEND);
                                    entrada = (string.toString() + "\n").getBytes();
                                    Files.write(Paths.get(FILEPATH), entrada, StandardOpenOption.APPEND);
                                    tablaDeSimbolos.add(token);

                                  } catch(Exception e) {
                                        e.printStackTrace();
                                        System.out.println("Error grabando en el archivo token ENTERO");
                                  }

                                  return token;
            } 
            // fall through
          case 75: break;
          case 23: 
            { string.append('\\');
            } 
            // fall through
          case 76: break;
          case 24: 
            { System.out.println("Reconoci un comentario");
            } 
            // fall through
          case 77: break;
          case 25: 
            { MiToken token = new MiToken("FLOTANTE", yytext());
                                  try {
                                    entrada = "FLOTANTE ".getBytes();
                                    Files.write(Paths.get(FILEPATH), entrada, StandardOpenOption.APPEND);
                                    entrada = (yytext() + "\n").getBytes();
                                    Files.write(Paths.get(FILEPATH), entrada, StandardOpenOption.APPEND);
                                    tablaDeSimbolos.add(token);

                                  } catch(Exception e) {
                                        e.printStackTrace();
                                        System.out.println("Error en grabando en el archivo token FLOTANTE");
                                  }

                                  return token;
            } 
            // fall through
          case 78: break;
          case 26: 
            { return token("EQUAL", yytext());
            } 
            // fall through
          case 79: break;
          case 27: 
            { return token("AND", yytext());
            } 
            // fall through
          case 80: break;
          case 28: 
            { return token("OR", yytext());
            } 
            // fall through
          case 81: break;
          case 29: 
            { return token("DIFF", yytext());
            } 
            // fall through
          case 82: break;
          case 30: 
            { return token("MENOREQUAL", yytext());
            } 
            // fall through
          case 83: break;
          case 31: 
            { return token("MAYOREQUAL", yytext());
            } 
            // fall through
          case 84: break;
          case 32: 
            { return token("IS", yytext());
            } 
            // fall through
          case 85: break;
          case 33: 
            { return token("IF", yytext());
            } 
            // fall through
          case 86: break;
          case 34: 
            { return token("DO", yytext());
            } 
            // fall through
          case 87: break;
          case 35: 
            { string.append('\n');
            } 
            // fall through
          case 88: break;
          case 36: 
            { string.append('\t');
            } 
            // fall through
          case 89: break;
          case 37: 
            { string.append('\r');
            } 
            // fall through
          case 90: break;
          case 38: 
            { string.append('\"');
            } 
            // fall through
          case 91: break;
          case 39: 
            { return token("TRUE", yytext());
            } 
            // fall through
          case 92: break;
          case 40: 
            { return token("FALSE", yytext());
            } 
            // fall through
          case 93: break;
          case 41: 
            { return token("INT", yytext());
            } 
            // fall through
          case 94: break;
          case 42: 
            { return token("MAIN", yytext());
            } 
            // fall through
          case 95: break;
          case 43: 
            { return token("SHOW", yytext());
            } 
            // fall through
          case 96: break;
          case 44: 
            { return token("THEN", yytext());
            } 
            // fall through
          case 97: break;
          case 45: 
            { return token("VARS", yytext());
            } 
            // fall through
          case 98: break;
          case 46: 
            { return token("ELSE", yytext());
            } 
            // fall through
          case 99: break;
          case 47: 
            { return token("CONST", yytext());
            } 
            // fall through
          case 100: break;
          case 48: 
            { return token("FLOAT", yytext());
            } 
            // fall through
          case 101: break;
          case 49: 
            { return token("WHILE", yytext());
            } 
            // fall through
          case 102: break;
          case 50: 
            { return token("UNTIL", yytext());
            } 
            // fall through
          case 103: break;
          case 51: 
            { return token("REPEAT", yytext());
            } 
            // fall through
          case 104: break;
          case 52: 
            { return token("BOOLEAN", yytext());
            } 
            // fall through
          case 105: break;
          case 53: 
            { return token("BETWEEN", yytext());
            } 
            // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
